### ISSUE TITLE
ENCAPSIA_URL and ENCAPSIA_TOKEN are not usable

### ISSUE THREAD

**Issue by gmosteoru** [tcorbettclark/encapsia-cli#50]
Code that reads environment variables if `host` is not supplied is not reachable, so the "Unable to determine host" message is returned to the user.

```python
def get_api(**obj):
    host = obj.get("host")
    if host is None:
        log_error("Unable to determine host.")
        log_error(
            "Please specify via the command line, env variable, or ~/.encapsia/config.toml file.",
            abort=True,
        )
    try:
        url, token = encapsia_api.discover_credentials(obj["host"])
    except encapsia_api.EncapsiaApiError as e:
```

**Comment by tcorbettclark** [comment]
The code needs to be re-arranged, since if `ENCAPSIA_HOST` is not set then `host` will be `None`, and no attempt to lookup `ENCAPSIA_URL` and `ENCAPSIA_TOKEN` will occur.

Note that we are using Click to read the env variables if not provided on the command line (or indeed, provided in the config file). Be sure to read https://github.com/tcorbettclark/encapsia-cli/blob/master/encapsia_cli/encapsia.py#L89 before working on this.
